name: Integration Test
on: [push , pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v2
        with:
          ref: ${{github.ref}}

      # create or connect to a new Workspace
      - name: Connect or Create Workspace
        id: ws_connect
        uses: azure/aml-workspace@v1
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          parameters_file: "test/test_workspace.json"

      # create or connect to compute
      - name: Connect or Create Compute AML
        id: ws_aml_compute
        uses: ./
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          parameters_file: "test/test_aml_compute.json"
      
      # create or connect to compute
      - name: Connect or Create Compute AKS
        id: ws_aks_compute
        uses: ./
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          parameters_file: "test/test_aks_compute.json"

      - uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az extension add -n azure-cli-ml
            az ml folder attach -w gha_and_aml_workspace  -g gha_and_aml_rg
            az ml computetarget delete --name "aks-intTest"
            az ml computetarget delete --name "aml-intTest"
