name: Integration Test
on: [push , pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v2
        with:
          ref: ${{github.ref}}

      # create or connect to a new Workspace
      - name: Connect or Create Workspace
        id: ws_connect
        uses: azure/aml-workspace@v1
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          parameters_file: "test/test_workspace.json"
      
      # create or connect to compute
      - name: Connect or Create Compute AKS
        id: ws_aks_compute
        uses: ./
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          parameters_file: "test/test_aks_compute.json"
          resource_grp: "attachaks"
